import { Codex, weighted, Species } from "../index.ts";
import preload from "../preload.ts";

export const Bulbasaur: Species = preload.register((C: Codex) => ({
  name: "Bulbasaur",
  description:
    "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger. While it is young, it uses the nutrients that are stored in the seed in order to grow.",
  types: [C.Types.Grass, C.Types.Poison],
  baseStats: {
    hp: 45,
    attack: 49,
    defense: 49,
    specialAttack: 65,
    specialDefense: 65,
    speed: 45,
  },
  abilities: {
    normal: [C.Abilities.Overgrow],
    hidden: C.Abilities.Chlorophyll,
  },
  genders: weighted([
    [C.Genders.Male, 7],
    [C.Genders.Female, 1],
  ]),
  evYields: { specialAttack: 1 },
  baseExperienceYield: 64,
  evolutions: [
    [C.Species.Ivysaur, { level: 16 }],
    [C.Species.Pikachu, { item: C.Items.SunStone }],
  ],
  experienceGroup: C.Experience.MedSlow,
  catchRate: 45,
  eggCycles: 21, // (5396+1) / 257
  height: 0.7,
  weight: 6.9,
  bodyType: "Quadruped",
  baseFriendship: 70,
  learnset: {
    1: [C.Moves.Tackle, C.Moves.Growl],
    3: [C.Moves.VineWhip],
    6: [C.Moves.Growth],
    9: [C.Moves.LeechSeed],
    12: [C.Moves.RazorLeaf],
    15: [C.Moves.PoisonPowder, C.Moves.SleepPowder],
    18: [C.Moves.SeedBomb],
    21: [C.Moves.TakeDown],
    24: [C.Moves.SweetScent],
    27: [C.Moves.Synthesis],
    30: [C.Moves.WorrySeed],
    33: [C.Moves.DoubleEdge],
    36: [C.Moves.SolarBeam],
    breeding: [
      [
        [
          C.Species.Slowpoke,
          C.Species.Slowbro,
          C.Species.Slowking,
          C.Species.Ferroseed,
          C.Species.Ferrothorn,
          C.Species.Phantump,
          C.Species.Trevenant,
          C.Species.Bergmite,
          C.Species.Avalugg,
          C.Species.Appletun,
        ],
        C.Moves.Curse,
      ],
      [
        [
          C.Species.Tangela,
          C.Species.Tangrowth,
          C.Species.Roselia,
          C.Species.Roserade,
          C.Species.Snover,
          C.Species.Abomasnow,
          C.Species.Maractus,
          C.Species.Foongus,
          C.Species.Amoonguss,
          C.Species.Ferroseed,
          C.Species.Ferrothorn,
          C.Species.Phantump,
          C.Species.Trevenant,
          C.Species.Fomantis,
          C.Species.Lurantis,
          C.Species.Morelull,
          C.Species.Shiinotic,
        ],
        C.Moves.Ingrain,
      ],
      [
        [C.Species.Lotad, C.Species.Lombre, C.Species.Ludicolo, C.Species.Seedot, C.Species.Nuzleaf, C.Species.Shiftry],
        C.Moves.NaturePower,
      ],
      [
        [
          C.Species.Venusaur,
          C.Species.Oddish,
          C.Species.Gloom,
          C.Species.Vileplume,
          C.Species.Bellossom,
          C.Species.Roselia,
          C.Species.Roserade,
          C.Species.Cherrim,
          C.Species.Maractus,
          C.Species.Comfey,
        ],
        C.Moves.PetalDance,
      ],
      [[C.Species.Squirtle, C.Species.Wartortle, C.Species.Blastoise, C.Species.Avalugg], C.Moves.SkullBash],
      [
        [
          C.Species.NidoranM,
          C.Species.Nidorino,
          C.Species.Nidoking,
          C.Species.Oddish,
          C.Species.Gloom,
          C.Species.Vileplume,
          C.Species.Bellossom,
          C.Species.Roselia,
          C.Species.Roserade,
          C.Species.Foongus,
          C.Species.Amoonguss,
          C.Species.Salandit,
        ],
        C.Moves.Toxic,
      ],
    ],
    machine: [
      C.Moves.MagicalLeaf,
      C.Moves.SolarBeam,
      C.Moves.LightScreen,
      C.Moves.Safeguard,
      C.Moves.Rest,
      C.Moves.Snore,
      C.Moves.Protect,
      C.Moves.GigaDrain,
      C.Moves.Charm,
      C.Moves.Attract,
      C.Moves.SunnyDay,
      C.Moves.Facade,
      C.Moves.HelpingHand,
      C.Moves.WeatherBall,
      C.Moves.BulletSeed,
      C.Moves.Venoshock,
      C.Moves.Round,
      C.Moves.GrassyTerrain,
      C.Moves.FalseSwipe,
      C.Moves.SwordsDance,
      C.Moves.BodySlam,
      C.Moves.Amnesia,
      C.Moves.Substitute,
      C.Moves.SludgeBomb,
      C.Moves.Endure,
      C.Moves.SleepTalk,
      C.Moves.SeedBomb,
      C.Moves.EnergyBall,
      C.Moves.LeafStorm,
      C.Moves.PowerWhip,
      C.Moves.GrassKnot,
      C.Moves.WorkUp,
    ],
    tutoring: [C.Moves.GrassPledge, C.Moves.GrassyGlide],
  },
}));
